// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KCPGrpcService.proto

package kcp.aio.server.job.verify;

public interface GrpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kcpgrpc.GrpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float t0 = 1;</code>
   */
  float getT0();

  /**
   * <code>float t1 = 2;</code>
   */
  float getT1();

  /**
   * <code>float t2 = 3;</code>
   */
  float getT2();

  /**
   * <code>float t3 = 4;</code>
   */
  float getT3();

  /**
   * <code>float t4 = 5;</code>
   */
  float getT4();

  /**
   * <code>float t5 = 6;</code>
   */
  float getT5();

  /**
   * <code>float t6 = 7;</code>
   */
  float getT6();

  /**
   * <code>float t7 = 8;</code>
   */
  float getT7();

  /**
   * <code>float t8 = 9;</code>
   */
  float getT8();

  /**
   * <code>float t9 = 10;</code>
   */
  float getT9();

  /**
   * <code>string re = 11;</code>
   */
  java.lang.String getRe();
  /**
   * <code>string re = 11;</code>
   */
  com.google.protobuf.ByteString
      getReBytes();
}
