// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KCPGrpcService.proto

package kcp.aio.server.job.verify;

public final class KCPProto {
  private KCPProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kcpgrpc_GrpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kcpgrpc_GrpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kcpgrpc_GrpcReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kcpgrpc_GrpcReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024KCPGrpcService.proto\022\007kcpgrpc\"\221\001\n\013Grpc" +
      "Request\022\n\n\002t0\030\001 \001(\002\022\n\n\002t1\030\002 \001(\002\022\n\n\002t2\030\003 " +
      "\001(\002\022\n\n\002t3\030\004 \001(\002\022\n\n\002t4\030\005 \001(\002\022\n\n\002t5\030\006 \001(\002\022" +
      "\n\n\002t6\030\007 \001(\002\022\n\n\002t7\030\010 \001(\002\022\n\n\002t8\030\t \001(\002\022\n\n\002t" +
      "9\030\n \001(\002\022\n\n\002re\030\013 \001(\t\"\034\n\tGrpcReply\022\017\n\007mess" +
      "age\030\001 \001(\t2A\n\007Greeter\0226\n\010CallGrpc\022\024.kcpgr" +
      "pc.GrpcRequest\032\022.kcpgrpc.GrpcReply\"\000B-\n\031" +
      "kcp.aio.server.job.verifyB\010KCPProtoP\001\242\002\003" +
      "HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kcpgrpc_GrpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kcpgrpc_GrpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kcpgrpc_GrpcRequest_descriptor,
        new java.lang.String[] { "T0", "T1", "T2", "T3", "T4", "T5", "T6", "T7", "T8", "T9", "Re", });
    internal_static_kcpgrpc_GrpcReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kcpgrpc_GrpcReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kcpgrpc_GrpcReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
