// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KCPGrpcService.proto

package kr.kcp.aio.grpc;

/**
 * <pre>
 * The request message containing the user's name.
 * </pre>
 *
 * Protobuf type {@code kcpgrpc.GrpcRequest}
 */
public  final class GrpcRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kcpgrpc.GrpcRequest)
    GrpcRequestOrBuilder {
  // Use GrpcRequest.newBuilder() to construct.
  private GrpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcRequest() {
    inMessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GrpcRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              inputParams_ = com.google.protobuf.MapField.newMapField(
                  InputParamsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            inputParams__ = input.readMessage(
                InputParamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            inputParams_.getMutableMap().put(
                inputParams__.getKey(), inputParams__.getValue());
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            inMessage_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kr.kcp.aio.grpc.KCPProto.internal_static_kcpgrpc_GrpcRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetInputParams();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kr.kcp.aio.grpc.KCPProto.internal_static_kcpgrpc_GrpcRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kr.kcp.aio.grpc.GrpcRequest.class, kr.kcp.aio.grpc.GrpcRequest.Builder.class);
  }

  private int bitField0_;
  public static final int INPUTPARAMS_FIELD_NUMBER = 1;
  private static final class InputParamsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                kr.kcp.aio.grpc.KCPProto.internal_static_kcpgrpc_GrpcRequest_InputParamsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> inputParams_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetInputParams() {
    if (inputParams_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          InputParamsDefaultEntryHolder.defaultEntry);
    }
    return inputParams_;
  }

  public int getInputParamsCount() {
    return internalGetInputParams().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; inputParams = 1;</code>
   */

  public boolean containsInputParams(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetInputParams().getMap().containsKey(key);
  }
  /**
   * Use {@link #getInputParamsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getInputParams() {
    return getInputParamsMap();
  }
  /**
   * <code>map&lt;string, string&gt; inputParams = 1;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getInputParamsMap() {
    return internalGetInputParams().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; inputParams = 1;</code>
   */

  public java.lang.String getInputParamsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetInputParams().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; inputParams = 1;</code>
   */

  public java.lang.String getInputParamsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetInputParams().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int INMESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object inMessage_;
  /**
   * <code>string inMessage = 2;</code>
   */
  public java.lang.String getInMessage() {
    java.lang.Object ref = inMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string inMessage = 2;</code>
   */
  public com.google.protobuf.ByteString
      getInMessageBytes() {
    java.lang.Object ref = inMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetInputParams(),
        InputParamsDefaultEntryHolder.defaultEntry,
        1);
    if (!getInMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, inMessage_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetInputParams().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      inputParams__ = InputParamsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, inputParams__);
    }
    if (!getInMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, inMessage_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kr.kcp.aio.grpc.GrpcRequest)) {
      return super.equals(obj);
    }
    kr.kcp.aio.grpc.GrpcRequest other = (kr.kcp.aio.grpc.GrpcRequest) obj;

    boolean result = true;
    result = result && internalGetInputParams().equals(
        other.internalGetInputParams());
    result = result && getInMessage()
        .equals(other.getInMessage());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetInputParams().getMap().isEmpty()) {
      hash = (37 * hash) + INPUTPARAMS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetInputParams().hashCode();
    }
    hash = (37 * hash) + INMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getInMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kr.kcp.aio.grpc.GrpcRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.kcp.aio.grpc.GrpcRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.kcp.aio.grpc.GrpcRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.kcp.aio.grpc.GrpcRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.kcp.aio.grpc.GrpcRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.kcp.aio.grpc.GrpcRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.kcp.aio.grpc.GrpcRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.kcp.aio.grpc.GrpcRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.kcp.aio.grpc.GrpcRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kr.kcp.aio.grpc.GrpcRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.kcp.aio.grpc.GrpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.kcp.aio.grpc.GrpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kr.kcp.aio.grpc.GrpcRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request message containing the user's name.
   * </pre>
   *
   * Protobuf type {@code kcpgrpc.GrpcRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kcpgrpc.GrpcRequest)
      kr.kcp.aio.grpc.GrpcRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kr.kcp.aio.grpc.KCPProto.internal_static_kcpgrpc_GrpcRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetInputParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableInputParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kr.kcp.aio.grpc.KCPProto.internal_static_kcpgrpc_GrpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kr.kcp.aio.grpc.GrpcRequest.class, kr.kcp.aio.grpc.GrpcRequest.Builder.class);
    }

    // Construct using kr.kcp.aio.grpc.GrpcRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      internalGetMutableInputParams().clear();
      inMessage_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kr.kcp.aio.grpc.KCPProto.internal_static_kcpgrpc_GrpcRequest_descriptor;
    }

    public kr.kcp.aio.grpc.GrpcRequest getDefaultInstanceForType() {
      return kr.kcp.aio.grpc.GrpcRequest.getDefaultInstance();
    }

    public kr.kcp.aio.grpc.GrpcRequest build() {
      kr.kcp.aio.grpc.GrpcRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kr.kcp.aio.grpc.GrpcRequest buildPartial() {
      kr.kcp.aio.grpc.GrpcRequest result = new kr.kcp.aio.grpc.GrpcRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.inputParams_ = internalGetInputParams();
      result.inputParams_.makeImmutable();
      result.inMessage_ = inMessage_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kr.kcp.aio.grpc.GrpcRequest) {
        return mergeFrom((kr.kcp.aio.grpc.GrpcRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kr.kcp.aio.grpc.GrpcRequest other) {
      if (other == kr.kcp.aio.grpc.GrpcRequest.getDefaultInstance()) return this;
      internalGetMutableInputParams().mergeFrom(
          other.internalGetInputParams());
      if (!other.getInMessage().isEmpty()) {
        inMessage_ = other.inMessage_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kr.kcp.aio.grpc.GrpcRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kr.kcp.aio.grpc.GrpcRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> inputParams_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetInputParams() {
      if (inputParams_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            InputParamsDefaultEntryHolder.defaultEntry);
      }
      return inputParams_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableInputParams() {
      onChanged();;
      if (inputParams_ == null) {
        inputParams_ = com.google.protobuf.MapField.newMapField(
            InputParamsDefaultEntryHolder.defaultEntry);
      }
      if (!inputParams_.isMutable()) {
        inputParams_ = inputParams_.copy();
      }
      return inputParams_;
    }

    public int getInputParamsCount() {
      return internalGetInputParams().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; inputParams = 1;</code>
     */

    public boolean containsInputParams(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetInputParams().getMap().containsKey(key);
    }
    /**
     * Use {@link #getInputParamsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getInputParams() {
      return getInputParamsMap();
    }
    /**
     * <code>map&lt;string, string&gt; inputParams = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getInputParamsMap() {
      return internalGetInputParams().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; inputParams = 1;</code>
     */

    public java.lang.String getInputParamsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetInputParams().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; inputParams = 1;</code>
     */

    public java.lang.String getInputParamsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetInputParams().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearInputParams() {
      internalGetMutableInputParams().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; inputParams = 1;</code>
     */

    public Builder removeInputParams(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableInputParams().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableInputParams() {
      return internalGetMutableInputParams().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; inputParams = 1;</code>
     */
    public Builder putInputParams(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableInputParams().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; inputParams = 1;</code>
     */

    public Builder putAllInputParams(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableInputParams().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.lang.Object inMessage_ = "";
    /**
     * <code>string inMessage = 2;</code>
     */
    public java.lang.String getInMessage() {
      java.lang.Object ref = inMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string inMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInMessageBytes() {
      java.lang.Object ref = inMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string inMessage = 2;</code>
     */
    public Builder setInMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string inMessage = 2;</code>
     */
    public Builder clearInMessage() {
      
      inMessage_ = getDefaultInstance().getInMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string inMessage = 2;</code>
     */
    public Builder setInMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inMessage_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:kcpgrpc.GrpcRequest)
  }

  // @@protoc_insertion_point(class_scope:kcpgrpc.GrpcRequest)
  private static final kr.kcp.aio.grpc.GrpcRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kr.kcp.aio.grpc.GrpcRequest();
  }

  public static kr.kcp.aio.grpc.GrpcRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcRequest>
      PARSER = new com.google.protobuf.AbstractParser<GrpcRequest>() {
    public GrpcRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GrpcRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GrpcRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcRequest> getParserForType() {
    return PARSER;
  }

  public kr.kcp.aio.grpc.GrpcRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

