// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KCPGrpcService.proto

package kr.kcp.aio.grpc;

public interface GrpcReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kcpgrpc.GrpcReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string outMessage = 1;</code>
   */
  java.lang.String getOutMessage();
  /**
   * <code>string outMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getOutMessageBytes();
}
