// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KCPGrpcService.proto

package kr.kcp.aio.grpc;

public final class KCPProto {
  private KCPProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kcpgrpc_GrpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kcpgrpc_GrpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kcpgrpc_GrpcRequest_InputParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kcpgrpc_GrpcRequest_InputParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kcpgrpc_GrpcReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kcpgrpc_GrpcReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024KCPGrpcService.proto\022\007kcpgrpc\"\220\001\n\013Grpc" +
      "Request\022:\n\013inputParams\030\001 \003(\0132%.kcpgrpc.G" +
      "rpcRequest.InputParamsEntry\022\021\n\tinMessage" +
      "\030\002 \001(\t\0322\n\020InputParamsEntry\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\t:\0028\001\"\037\n\tGrpcReply\022\022\n\noutMe" +
      "ssage\030\001 \001(\t2D\n\nKcpService\0226\n\010CallGrpc\022\024." +
      "kcpgrpc.GrpcRequest\032\022.kcpgrpc.GrpcReply\"" +
      "\000B#\n\017kr.kcp.aio.grpcB\010KCPProtoP\001\242\002\003HLWb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kcpgrpc_GrpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kcpgrpc_GrpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kcpgrpc_GrpcRequest_descriptor,
        new java.lang.String[] { "InputParams", "InMessage", });
    internal_static_kcpgrpc_GrpcRequest_InputParamsEntry_descriptor =
      internal_static_kcpgrpc_GrpcRequest_descriptor.getNestedTypes().get(0);
    internal_static_kcpgrpc_GrpcRequest_InputParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kcpgrpc_GrpcRequest_InputParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_kcpgrpc_GrpcReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kcpgrpc_GrpcReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kcpgrpc_GrpcReply_descriptor,
        new java.lang.String[] { "OutMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
